version: '3.7'

services:
  project:
    build: .
    container_name: project_app
    command: python /app/project/api/main.py
    environment:
      - DB_CONNECTION_STRING=mongodb://root:password@db:27017/admin?retryWrites=true&w=majority
      - DB_NAME=project_db
      - ENVIRONMENT=dev
    volumes:
      - ./project:/app/project
      - ./test:/app/test
      - ./mypy.ini:/app/mypy.ini
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./Makefile:/app/Makefile
      - ./coverage-reports:/code/coverage-reports
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    container_name: project_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
